#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int abstractWheelViewStyle = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int isAllVisible = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int isCyclic = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int itemOffsetPercent = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int itemsDimmedAlpha = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int itemsPadding = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int selectionDivider = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int selectionDividerActiveAlpha = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int selectionDividerDimmedAlpha = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int selectionDividerHeight = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int selectionDividerWidth = 2130771978;
			
			// aapt resource value: 0x7f010001
			public const int visibleItems = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int wheel_bg_hor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int wheel_bg_ver = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int wheel_val = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int wheel_text_view_configured_state = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AbstractWheelView = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int AbstractWheelView_isAllVisible = 1;
			
			// aapt resource value: 8
			public const int AbstractWheelView_isCyclic = 8;
			
			// aapt resource value: 2
			public const int AbstractWheelView_itemOffsetPercent = 2;
			
			// aapt resource value: 7
			public const int AbstractWheelView_itemsDimmedAlpha = 7;
			
			// aapt resource value: 3
			public const int AbstractWheelView_itemsPadding = 3;
			
			// aapt resource value: 6
			public const int AbstractWheelView_selectionDivider = 6;
			
			// aapt resource value: 5
			public const int AbstractWheelView_selectionDividerActiveAlpha = 5;
			
			// aapt resource value: 4
			public const int AbstractWheelView_selectionDividerDimmedAlpha = 4;
			
			// aapt resource value: 0
			public const int AbstractWheelView_visibleItems = 0;
			
			public static int[] WheelHorizontalView = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int WheelHorizontalView_selectionDividerWidth = 0;
			
			public static int[] WheelVerticalView = new int[] {
					2130771979};
			
			// aapt resource value: 0
			public const int WheelVerticalView_selectionDividerHeight = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
